trigger:
  tags:
    include:
      - "*"
  branches:
    include:
      - "*"

pr:
  branches:
    include:
      - develop
      - master

resources:
  repositories:
    - repository: templates
      type: git
      name: pipeline-templates-v2
      ref: develop

pool:
  vmImage: ubuntu-latest

extends:
  template: pipelines/js-docker.yml@templates
  parameters:
    projectName: template
    repoName: express-typescript-starter
    containerRegistry: acr-builder
    nodeVersion: 24.14.1
