# Project identification
sonar.projectKey=express-typescript-starter
sonar.projectName=Express Typescript Starter
 
# Project sources
sonar.sources=src
 
# Language configuration
sonar.language=ts
 
# Encoding of the source files
sonar.sourceEncoding=UTF-8

# Exclude test files and directories
sonar.exclusions=**/*.test.ts
 
# Test coverage report
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Test coverage exclusions
sonar.coverage.exclusions=src/app.ts, src/utils/keyVault.ts, src/utils/testUtils/**, src/**/index.ts, src/models/**, src/openapi/**, src/typings/**